apiVersion: apps/v1
kind: Deployment
metadata:
  name: lynx
  namespace: lynx
  labels:
    app: lynx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lynx
  template:
    metadata:
      labels:
        app: lynx
    spec:
      imagePullSecrets:
        - name: docker-registry-creds
      containers:
        - name: lynx
          image: {{ .Values.yapper.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
